### ISSUE TITLE
No Slack Notifications

### ISSUE THREAD

**Issue by nordwynd-ds** [ngraf/slack-codeception-extension#12]
Unfortunately, even with everything correct installed, no notifications were received in slack.

Tested it with setting the extension active via `Codeception.yaml` and as an alternative, via the command line `--ext SlackExtension`

I had installed a second extension 'ProgressReporter', just to get sure, everything's on the Codeception side ist fully functional. And Progress Reporter runs just fine...

Verbose output doesn't even mention SlackExtension....

am I missing something?

Here is my Codeception.yaml:

```
extensions:
    enabled:
        - Codeception\ProgressReporter\ProgressReporter
        - Codeception\Extension\SlackExtension
    config:
        Codeception\Extension\SlackExtension:
            messagePrefix: '*Smoke-Test*'
            webhook: https://hooks.slack.com/services/...
            strategy: always
            extended: true
            extendedMaxLength: 150
            channel: '#channelname'
```
