### ISSUE TITLE
Different configs for environments

### ISSUE THREAD

**Issue by Shiriaev** [ngraf/slack-codeception-extension#9]
Hello!

Is it possible to use different configs for environments? For example, enable notifications only for specific environment, not for all?

Thanks

**Comment by ngraf** [comment]
Yes, I think so.

Look at the the example at https://codeception.com/docs/07-AdvancedUsage#Current-values module how to achieve this.

In this case you can try:
```
env:
    development:
         # extension not enabled
    production:
         extensions:
            enabled:
               - Codeception\Extension\SlackExtension
    
```

But what I personally prefer is the configuration via command line. I always have the extension inactive in yaml configuration. Then I add `--ext SlackExtension` to my `codecept run --ext SlackExtension` to activate it. In local mode I don't add it, in my remote CI/CD pipelines it is added as parameter in the pipeline.
If this was helpful, then please let me know.

**Comment by Shiriaev** [comment]
Only one variant is working.
codeception.yml:

```
extensions:
  config:
    Codeception\Extension\SlackExtension:
      messagePrefix: '*Smoke-Test*'
      webhook: https://hooks.slack.com/services/...
      strategy: always
      extended: true
      extendedMaxLength: 150
      channel: '#any-channel'
```

And then 
`
php codecept --debug run api --ext SlackExtension
`

variant with 

```
env:
    development:
         # extension not enabled
    production:
         extensions:
            enabled:
               - Codeception\Extension\SlackExtension
```
Not working.
It would be great if you could set different prefixes for different environments, for example

``` 
messagePrefix: '*DEV Smoke-Test*'
messagePrefix: '*STAGE Smoke-Test*'
messagePrefix: 'PROD *Smoke-Test*'
```
